CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "name" varchar(30) NOT NULL,
  "email" varchar(30),
  "password" varchar(30),
  "age" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level_course_id" int NOT NULL,
  "title" varchar(100),
  "description" varchar(30)
);

CREATE TABLE "level_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level_name" varchar(15)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_roles" varchar(15)
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int,
  "title" varchar(40),
  "url" varchar
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_categories" varchar(30)
);

CREATE TABLE "courses_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int,
  "users_id" int
);

CREATE TABLE "cateogory_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "category_id" int
);

ALTER TABLE "courses_video" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_user" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_user" ADD FOREIGN KEY ("users_id") REFERENCES "user" ("id");

ALTER TABLE "cateogory_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "cateogory_courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_course_id") REFERENCES "level_courses" ("id");


SCRIPTS DE LOS LEVELS DE CURSOS: ✔

task1_db=# INSERT INTO level_courses (level_name) VALUES ('beginners'), ('middle'), ('advanced');
INSERT 0 3



SCRIPTS DE LOS ROLES:✔

task1_db=# INSERT INTO roles (name_roles) VALUES ('Administrator'),('Teacher'),('Student');
INSERT 0 3


SCRIPTS DE LAS CATEGORIAS DE LOS CURSOS:✔

task1_db=# INSERT INTO categories (name_categories) VALUES ('Data Science'),('Back-End'),('Front-End');
INSERT 0 3



SCRIPTS DE LOS CURSOS:✔
task1_db=# INSERT INTO courses (level_course_id, title, description) VALUES (1 ,'Phyton, el lenguaje de la IA', 'Generar procesos ia');

task1_db=# INSERT INTO courses (level_course_id, title, description) VALUES (2 ,'PostgresSQL', 'Creamos base de datos');
INSERT 0 1
task1_db=# INSERT INTO courses (level_course_id, title, description) VALUES (3 ,'PostgresSQL', 'Creamos base de datos');
task1_db=# \d user



SCRIPTS DE LOS USUARIOS:✔
task1_db=# INSERT INTO public.user(role_id, name, email, password, age) VALUES (2, 'belen', 'email@email.com' , '1234', 24);

INSERT INTO public.user(role_id, name, email, password, age) VALUES (2, 'Diego', 'emai.l@email.com' , '1234', 26);
 INSERT INTO public.user(role_id, name, email, password, age) VALUES (1, 'Aurora', 'email.academlo@email.com' , '1234', 26);


Script de los videos de cursos: ✔

 INSERT INTO courses_video(courses_id, title, url) VALUES (1, 'primera clase', 'www.url.com');
 INSERT INTO courses_video(courses_id, title, url) VALUES (1, 'segunda clase', 'www.url.com'),(3, 'primera clase psql', 'www.urlpsql.com');
